version: '3.1'
services:
  database:
    build: ./database
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db-data/:/var/lib/mysql
      - ./database/backup:/backup
      - ./backend/.env:/.env
    # labels:
    #   - 'traefik.enable=false'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database
    # labels:
    #   - 'traefik.backend=adminer-${DOMAIN}'
    #   - 'traefik.frontend.rule=Host:adminer.${DOMAIN}.localhost'
    #   - 'traefik.port=8080'
  
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - /var/www/app/node_modules
      - ./backend:/var/www/app
    depends_on:
      - database
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8000:3000
    # labels:
    #   - 'traefik.backend=backend-${DOMAIN}'
    #   - 'traefik.frontend.rule=Host:backend.${DOMAIN}.localhost'
    #   - 'traefik.port=80'