service: serverless-graphql
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    host: 0.0.0.0
    babelOptions:
      presets: ["es2015", "stage-2"]
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get