service: turing-backend
plugins:
  - serverless-webpack
  - serverless-offline-dotenv
  - serverless-offline
custom:
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
    includeModules:
      packagePath: ./package.json
      forceInclude:
        - sequelize
        - mariadb
  serverless-offline:
    host: 0.0.0.0
    babelOptions:
      presets: ["es2015", "stage-2"]
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-1
  vpc:
    securityGroupIds:
      - ${env:lambdaExecSecurityGroup}
    subnetIds:
      - ${env:subnetAPrivate}
      - ${env:subnetBPrivate}
      # - ${env:subnetCPrivate}
functions:
  turing_graphql:
    handler: index.handler
    environment:
      NODE_ENV: ${env:NODE_ENV}
      DB_MACHINE: ${env:DB_MACHINE}
      DEPLOY_DB_DATABASE: ${env:DEPLOY_DB_DATABASE}
      DEPLOY_DB_HOST: ${env:DEPLOY_DB_HOST}
      DEPLOY_DB_PASSWORD: ${env:DEPLOY_DB_PASSWORD}
      DEPLOY_DB_PORT: ${env:DEPLOY_DB_PORT}
      DEPLOY_DB_USER: ${env:DEPLOY_DB_USER}
      SECRET: ${env:SECRET}
    events:
      - http:
          path: graphql
          method: post
          cors: true
  turing_playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get