service: serverless-graphql
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
    includeModules: true
    webpackIncludeModules:
      forceInclude:
        - pg
        - pg-hstore
        - mariadb
        - mysql2
  serverless-offline:
    host: 0.0.0.0
    babelOptions:
      presets: ["es2015", "stage-2"]
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
functions:
  graphql:
    handler: index.handler
    environment:
      DEPLOY_DB_HOST: db-turing.cgtjekwuvtry.us-west-2.rds.amazonaws.com
      DEPLOY_DB_DATABASE: dbturing
      DEPLOY_DB_USER: turing
      DEPLOY_DB_PASSWORD: passturing
      DEPLOY_DB_PORT: 3306
      SECRET: turing
      DB_MACHINE: mariadb
      NODE_ENV: production
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get