version: 2
references:
  container_config: &container_config
    working_directory: ~/tmp
    docker:
      - image: ronnf89/turing-backend:latest
  add_workspace: &add_workspace
    attach_workspace:
      at: .
  app_deploy: &app_deploy
    steps:
      - *add_workspace
      - deploy:
          name: Deploy app
          command: |
            yarn --cwd ~/tmp/backend sls deploy -v --stage $RELEASE_CHANNEL
jobs:
  checkout:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/tmp/backend/yarn.lock" }}
      - run:
          name: Check yarn version
          command: yarn --version
      - run:
          name: Install Dependencies
          command: yarn --cwd ~/tmp/backend install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/tmp/backend/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_models:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: check env var
          command: |
            echo $DEPLOY_DB_HOST
      - run:
          name: Build models from database
          command: sequelize-auto -h $DEPLOY_DB_HOST -d $DEPLOY_DB_DATABASE -u $DEPLOY_DB_USER -x $DEPLOY_DB_PASSWORD -p $DEPLOY_DB_PORT --dialect $DB_MACHINE -c ~/tmp/backend/src/config/dbconfig.json -o ~/tmp/backend/src/models
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: Run eslint
          command: yarn --cwd ~/tmp/backend lint
      - run:
          name: Run stylelint
          command: yarn --cwd ~/tmp/backend stylelint
      # - run:
      #     name: Run flow type check
      #     command: yarn --cwd ~/tmp/backend flow
  test:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: Run tests
          command: yarn --cwd ~/tmp/backend test
  deploy-app-pull-request:
    <<: *container_config
    environment:
      RELEASE_CHANNEL: pull-request
      NODE_ENV: production
      DEPLOY_DB_HOST: $DEPLOY_DB_HOST
      DEPLOY_DB_DATABASE: $DEPLOY_DB_DATABASE
      DEPLOY_DB_USER: $DEPLOY_DB_USER
      DEPLOY_DB_PASSWORD: $DEPLOY_DB_PASSWORD
      DEPLOY_DB_PORT: $DEPLOY_DB_PORT
      DB_MACHINE: $DB_MACHINE
      SECRET: $SECRET
    <<: *app_deploy
  deploy-app-staging:
    <<: *container_config
    environment:
      RELEASE_CHANNEL: dev
      NODE_ENV: production
      DEPLOY_DB_HOST: $DEPLOY_DB_HOST
      DEPLOY_DB_DATABASE: $DEPLOY_DB_DATABASE
      DEPLOY_DB_USER: $DEPLOY_DB_USER
      DEPLOY_DB_PASSWORD: $DEPLOY_DB_PASSWORD
      DEPLOY_DB_PORT: $DEPLOY_DB_PORT
      DB_MACHINE: $DB_MACHINE
      SECRET: $SECRET
    <<: *app_deploy
  deploy-app-production:
    <<: *container_config
    environment:
      RELEASE_CHANNEL: prod
      NODE_ENV: production
      DEPLOY_DB_HOST: $DEPLOY_DB_HOST
      DEPLOY_DB_DATABASE: $DEPLOY_DB_DATABASE
      DEPLOY_DB_USER: $DEPLOY_DB_USER
      DEPLOY_DB_PASSWORD: $DEPLOY_DB_PASSWORD
      DEPLOY_DB_PORT: $DEPLOY_DB_PORT
      DB_MACHINE: $DB_MACHINE
      SECRET: $SECRET
    <<: *app_deploy

workflows:
  version: 2
  deploy:
    jobs:
      - checkout
      - build_models:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
            - build_models
      - test:
          requires:
            - checkout
            - build_models
      - approve-deploy-pull-request:
          type: approval
          filters:
            branches:
              ignore: master
      - deploy-app-pull-request:
          requires:
            - lint
            - test
            - approve-deploy-pull-request
          filters:
            branches:
              ignore: master
      - deploy-app-staging:
          requires:
            - build_models
            - lint
            - test
          filters:
            branches:
              only: master